import {NgModule} from '@angular/core';
import {NZ_ICONS, NzIconModule} from 'ng-zorro-antd/icon';


import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  SecurityScanOutline,
  SyncOutline,
  ReadOutline,
  UserOutline,
  FileSearchOutline,
  TableOutline,
  GlobalOutline,
  CustomerServiceOutline,
  MailOutline,
  FilePdfOutline,
  DeleteOutline,
  SwapOutline,
  WarningOutline,
  YoutubeOutline,
  FieldNumberOutline,
  RetweetOutline,
  AuditOutline,
  DollarOutline,
  FileTextOutline,
  ClearOutline,
  LeftCircleOutline,
  ProfileOutline,
  GroupOutline,
  SearchOutline,
  ReloadOutline,
  CloseCircleOutline,
  CheckCircleOutline,
  InfoCircleOutline,
  LoadingOutline,
  CalendarOutline,
  EyeOutline,
  LockOutline
} from '@ant-design/icons-angular/icons';

const icons = [
  MenuFoldOutline, 
  MenuUnfoldOutline, 
  DashboardOutline, 
  FormOutline, 
  SecurityScanOutline, 
  SyncOutline, 
  ReadOutline, 
  UserOutline, 
  FileSearchOutline, 
  TableOutline,
  GlobalOutline, 
  CustomerServiceOutline, 
  MailOutline, 
  FilePdfOutline,
  DeleteOutline, 
  SwapOutline,
  WarningOutline,
  YoutubeOutline,
  FieldNumberOutline,
  RetweetOutline,
  AuditOutline,
  DollarOutline,
  FileTextOutline,
  ClearOutline,
  LeftCircleOutline,
  ProfileOutline,
  GroupOutline,
  SearchOutline,
  ReloadOutline,
  CloseCircleOutline,
  CheckCircleOutline,
  InfoCircleOutline,
  LoadingOutline,
  CalendarOutline,
  EyeOutline,
  LockOutline
];

@NgModule({
  imports: [NzIconModule],
  exports: [NzIconModule],
  providers: [{provide: NZ_ICONS, useValue: icons}],
})
export class IconsProviderModule {
}