steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lq-fresa-internal',
      '-f', 'lq-internal/src/main/docker/Dockerfile.jvm',
      '.'
    ]

  # Paso 2: Push de la imagen al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lq-fresa-internal'
    ]

  # Esperar unos segundos para asegurar que la imagen esté disponible
  - name: 'alpine'
    entrypoint: 'sh'
    args: ['-c', 'sleep 100']

  # Paso 3: Desplegar la imagen en Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'gcloud',
      'run',
      'deploy',
      'lq-fresa-internal',
      '--image', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lq-fresa-internal:latest',
      '--platform', 'managed',
      '--region', 'us-west1',
      '--allow-unauthenticated'
    ]

images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lq-fresa-internal'

options:
  logging: CLOUD_LOGGING_ONLY
